In [6]:
import cv2
import tensorflow as tf

In [7]:
CATEGORIES = ['butterfly', 'cat', 'chicken', 'cow', 'dog', 'elephant', 'horse', 'sheep', 'spider', 'squirrel']

In [8]:
def prepare(filepath):
    IMG_SIZE = 224
    img_array = cv2.imread(filepath)
    new_array = cv2.resize(img_array, (IMG_SIZE, IMG_SIZE))
    return new_array.reshape(-1, IMG_SIZE, IMG_SIZE, 3)

In [9]:
model = tf.keras.models.load_model("animal10-CNN.model")

In [16]:
prediction = model.predict([prepare('dog.jpg')])
print(prediction)  # will be a list in a list.
print(CATEGORIES[int(prediction[0][0])])

1/1 [==============================] - 0s 20ms/step
[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
cat


In [17]:
prediction = model.predict([prepare('spider.jpg')])
print(prediction)  # will be a list in a list.
print(CATEGORIES[int(prediction[0][0])])

1/1 [==============================] - 0s 19ms/step
[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
cat


In [18]:
prediction = model.predict([prepare('horse.jpg')])
print(prediction)  # will be a list in a list.
print(CATEGORIES[int(prediction[0][0])])

1/1 [==============================] - 0s 19ms/step
[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
cat


In [21]:
prediction = model.predict([prepare('elephant.jpg')])
print(prediction)  # will be a list in a list.
print(CATEGORIES[int(prediction[0][0])])

1/1 [==============================] - 0s 19ms/step
[[0.         0.         0.         0.99603635 0.         0.00396368
  0.         0.         0.         0.        ]]
butterfly


In [22]:
prediction = model.predict([prepare('squirrel.jpg')])
print(prediction)  # will be a list in a list.
print(CATEGORIES[int(prediction[0][0])])

1/1 [==============================] - 0s 19ms/step
[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
cat


In [23]:
prediction = model.predict([prepare('chicken.jpg')])
print(prediction)  # will be a list in a list.
print(CATEGORIES[int(prediction[0][0])])

1/1 [==============================] - 0s 19ms/step
[[0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]]
butterfly
